object BuildDependenciesVersions {
    const val KOTLIN = "1.6.10"
    const val APPCOMPAT = "1.4.1"
    const val HILT = "2.38.1"
    const val COROUTINES = "1.6.2"
    const val LIFECYCLE = "2.4.1"
    const val COMPOSE = "1.1.1"
    const val ACTIVITY_COMPOSE = "1.4.0"
    const val CORE_KTX = "1.7.0"
    const val PAGING = "3.1.1"
    const val PAGING_COMPOSE = "1.0.0-alpha14"
    const val RETROFIT = "2.9.0"
    const val RETROFIT_MOSHI_CONVERTER = "2.4.0"
    const val MOSHI = "1.13.0"
    const val COIL_COMPOSE = "1.4.0"

    // Tests
    const val TEST_CORE = "1.4.0"
    const val JUNIT = "4.13.2"
    const val JUNIT_EXT = "1.1.2"
    const val ARCH_CORE = "2.1.0"
    const val COROUTINES_TEST = "1.6.0"
    const val TRUTH_EXT = "1.4.0"
    const val MOCKK = "1.10.2"
    const val TRUTH = "1.1.3"
    const val ESPRESSO = "3.4.0"
    const val MOCK_WEB_SERVER = "4.9.3"
}
