name: Android CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  static_analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Run Detekt
        run: ./gradlew clean detekt

      - name: Run ktlint
        run: ./gradlew ktlintCheck

      - name: Run Lint
        run: ./gradlew lint

  unit_testing:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Run Unit Tests
        run: ./gradlew clean test

  instrumented_testing:
    name: Instrumented Tests
    runs-on: macos-latest
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Gradle Cache
        uses: gradle/gradle-build-action@v2

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-32

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 32
          target: google_apis
          arch: x86_64
          channel: canary
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Run Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 32
          target: google_apis
          profile: Nexus 6
          arch: x86_64
          channel: canary
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedCheck --stacktrace

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: emulator_tests_32
          path: app/build/reports/androidTests
